In [1]:
import numpy as np

### Define Activate function and initialize Weight

In [2]:
W1 = np.array([[0.2, -0.3],
               [0.4, 0.1],
               [-0.5, 0.2]])

W2 = np.array([[-0.3],
               [-0.2]])

b1 = np.array([[-0.4,0.2]])
b2 = np.array([[0.1]])

In [3]:
sigmoid = lambda x: 1/(1 + np.exp(-x))

In [4]:
learning_rate = -0.9

### Set input $\vec{X}$ and output $\vec{Y}$

In [5]:
X = np.array([[1, 0, 1]])
Y = np.array([[1]])

### Feed forward

In [6]:
z1 = X.dot(W1) + b1
a1 = sigmoid(z1)
a1

array([[0.33181223, 0.52497919]])

In [7]:
z2 = a1.dot(W2) + b2
a2 = sigmoid(z2)
a2

array([[0.4738889]])

### Backward

In [8]:
err = Y - a2
err

array([[0.5261111]])

In [9]:
gredOut = a2*(1 - a2)*err
gredOut

array([[0.13116908]])

In [10]:
gredH = a1 * (1 - a1) * gredOut.dot(W2.T)
gredH

array([[-0.00872456, -0.00654209]])

#### Update Output Layter

In [11]:
W2 = W2 - learning_rate *  a1.T.dot(gredOut)

In [12]:
W2

array([[-0.26082885],
       [-0.13802507]])

In [13]:
b2 = b2 - learning_rate * gredOut

In [14]:
b2

array([[0.21805217]])

#### Update Hidden Layer

In [15]:
gredH

array([[-0.00872456, -0.00654209]])

In [16]:
W1 = W1 - learning_rate * X.T.dot(gredH)

In [17]:
W1

array([[ 0.19214789, -0.30588788],
       [ 0.4       ,  0.1       ],
       [-0.50785211,  0.19411212]])

In [18]:
b1 = b1 - learning_rate * gredH

In [19]:
b1

array([[-0.40785211,  0.19411212]])