In [1]:
import numpy as np

In [2]:
W1 = np.array([[0.2, -0.3],
               [0.4, 0.1],
               [-0.5, 0.2]])

W2 = np.array([[-0.3],
               [-0.2]])

b1 = np.array([[-0.4, 0.2]])
b2 = np.array([[0.1]])

In [3]:
sigmoid = lambda x: 1/(1 + np.exp(-x))
learning_rate = -0.9

In [4]:
X = np.array([[1, 0, 1]])
Y = np.array([[1]])

In [5]:
for _ in range(100):
    z1 = X.dot(W1) + b1
    a1 = sigmoid(z1)
    z2 = a1.dot(W2) + b2
    a2 = sigmoid(z2)

    err = Y - a2
    if err <= 0.01:
        break
    gredOut = a2*(1 - a2)*err
    gredH = a1 * (1 - a1) * gredOut.dot(W2.T)

    W2 = W2 - learning_rate *  a1.T.dot(gredOut)
    b2 = b2 - learning_rate * gredOut

    W1 = W1 - learning_rate * X.T.dot(gredH)
    b1 = b1 - learning_rate * gredH

In [6]:
err

array([[0.06926646]])

In [7]:
a2

array([[0.93073354]])

In [9]:
np.random.uniform(-1,1,[3,2])

array([[ 0.37263466,  0.32432849],
       [ 0.24178798, -0.27892379],
       [-0.10580403,  0.19448586]])

In [ ]:
class ANN:
    def __init__(self, X, y, hidden_node, learning_rate, activate, epoches=100, input_shape):
        self.hidden_node = hidden_node
        self.learning_rate = learning_rate
        self.activate = sigmoid
        self.epoches = epoches
        self.input_shape = input_shape
        self.Weight1 = np.random.uniform(-1, 1, [X.shape[1], hidden_node])
        self.Weight2 = np.random.uniform(-1, 1, [hidden_node, y.shape[1]])
        self.bias1 = np.random.uniform(-1, 1, [1, hidden_node])
        self.bias2 = np.random.uniform(-1, 1, [1, y.shape[1]])
        self.X = X
        self.y = y
        self.activate = sigmoid
        
    def train(self):
        for _ in range(self.epoches):
        z1 = self.X.dot(self.Weight1) + self.bias1
        a1 = self.activate(z1)
        z2 = a1.dot(self.Weight2) + self.bias2
        a2 = self.activate(z2)

        err = self.y - a2
        if err <= 0.01:
            break
            
        gredOut = a2*(1 - a2)*err
        gredH = a1 * (1 - a1) * gredOut.dot(self.Weight2.T)

        self.Weight2 = self.Weight2 - self.learning_rate *  a1.T.dot(gredOut)
        b2 = b2 - self.learning_rate * gredOut

        W1 = W1 - self.learning_rate * self.X.T.dot(gredH)
        b1 = b1 - self.learning_rate * gredH
        
    def predict(self,y_valid):
        pass